name = "afd750-wsdsg"
main = "worker.js"
compatibility_date = "2026-08-18"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = [ "/api/*" ]

[[d1_databases]]
binding = "DB"
database_name = "pd750-gewh43"
database_id = "681def5d-b65b-426a-9c7e-19861470571e"
